export const reviews = [
  {
    name: 'Charlie Taylor',
    username: '@charlietaylor',
    body: "Love this - absolutely stunning website! The only thing is, I think it is really important to build your own portfolio. This is especially true for designers - what kind of designer doesn't design their own portfolio haha! But, I think there's big potential with non-frontend devs, and other professionals.",
    img: 'https://avatar.vercel.sh/charlie',
  },
  {
    name: 'Alex Snov',
    username: '@alexsnov',
    body: 'Very beautiful UI bro !!!',
    img: 'https://avatar.vercel.sh/alex',
  },
  {
    name: 'Qizlar Akademiyasi',
    username: '@qizlarakademiyasi',
    body: 'Bro it is very awesome platform',
    img: 'https://avatar.vercel.sh/qizlar',
  },
  {
    name: 'Benjamin Schmidt',
    username: '@benjaminschmidt',
    body: 'Nice UI 🖤',
    img: 'https://avatar.vercel.sh/benjamin',
  },
  {
    name: 'Priyank Deep Singh',
    username: '@priyankdeep',
    body: 'Good work!',
    img: 'https://avatar.vercel.sh/priyank',
  },
  {
    name: 'Sarah Chen',
    username: '@sarahchen',
    body: 'This is exactly what I needed! The UI is so clean and intuitive.',
    img: 'https://avatar.vercel.sh/sarah',
  },
  {
    name: 'Marcus Johnson',
    username: '@marcusj',
    body: 'Game changer for portfolio creation. Absolutely love the features!',
    img: 'https://avatar.vercel.sh/marcus',
  },
  {
    name: 'Emma Wilson',
    username: '@emmaw',
    body: 'Finally, a portfolio platform that understands what developers need!',
    img: 'https://avatar.vercel.sh/emma',
  },
  {
    name: 'Sarah Chen',
    username: '@sarahchen',
    body: 'This is exactly what I needed! The UI is so clean and intuitive. Perfect for showcasing my data science projects.',
    img: 'https://avatar.vercel.sh/sarah',
  },
  {
    name: 'Marcus Johnson',
    username: '@marcusj',
    body: 'Game changer for portfolio creation. The templates are modern and professional. Absolutely love it!',
    img: 'https://avatar.vercel.sh/marcus',
  },
  {
    name: 'Emma Wilson',
    username: '@emmaw',
    body: 'Finally, a portfolio platform that understands what developers need! The customization options are fantastic.',
    img: 'https://avatar.vercel.sh/emma',
  },
  {
    name: 'David Kumar',
    username: '@davidk',
    body: 'As a backend developer, this is perfect. No more struggling with design decisions. Everything just works!',
    img: 'https://avatar.vercel.sh/david',
  },
  {
    name: 'Lisa Anderson',
    username: '@lisaand',
    body: 'The dark mode implementation is gorgeous. Plus, the responsive design works flawlessly on all devices.',
    img: 'https://avatar.vercel.sh/lisa',
  },
  {
    name: 'James Mitchell',
    username: '@jamesmitch',
    body: 'Love how easy it is to showcase my GitHub projects. The integration is seamless!',
    img: 'https://avatar.vercel.sh/james',
  },
  {
    name: 'Nina Rodriguez',
    username: '@ninar',
    body: 'Been using this for my UX portfolio - the analytics features are incredibly helpful for tracking engagement.',
    img: 'https://avatar.vercel.sh/nina',
  },
  {
    name: 'Tom Wilson',
    username: '@tomw',
    body: 'The SEO optimization features are top-notch. My portfolio is ranking much better now!',
    img: 'https://avatar.vercel.sh/tom',
  },
  {
    name: 'Sophia Zhang',
    username: '@sophiaz',
    body: 'As a freelancer, this platform has helped me land more clients. The professional look really makes a difference.',
    img: 'https://avatar.vercel.sh/sophia',
  },
  {
    name: 'Michael Brooks',
    username: '@michaelb',
    body: 'The mobile-first approach is evident. My portfolio looks amazing on phones and tablets!',
    img: 'https://avatar.vercel.sh/michael',
  },
]
